INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started parent process [3497]
INFO:     Started server process [3499]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Started server process [3500]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     127.0.0.1:48504 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:40008 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:56590 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:39600 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:39614 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:50384 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:59948 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:52812 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:52820 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:58216 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:35358 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:53538 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:39054 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:39070 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:33844 - "POST /get_documents HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/teacher_gpt/embed_api/api.py", line 100, in get_documents
    documentos = [df[df.hash_name == i].name.tolist()[0] for i in documentos]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable
INFO:     127.0.0.1:47132 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:47148 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:47154 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:59018 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:34162 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:34174 - "POST /get_documents HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/teacher_gpt/embed_api/api.py", line 100, in get_documents
    documentos = [df[df.hash_name == i].name.tolist()[0] for i in documentos]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable
INFO:     127.0.0.1:34180 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:50886 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:55756 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:38052 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:60146 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:51468 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:51470 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:42862 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:42866 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:52796 - "POST /context HTTP/1.1" 200 OK
INFO:     127.0.0.1:33960 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:38318 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:34202 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:59796 - "POST /get_documents HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/teacher_gpt/embed_api/api.py", line 100, in get_documents
    documentos = [df[df.hash_name == i].name.tolist()[0] for i in documentos]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable
INFO:     127.0.0.1:59802 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:54422 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:42322 - "POST /load_context HTTP/1.1" 200 OK
INFO:     127.0.0.1:40782 - "POST /get_documents HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/applications.py", line 273, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 237, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/miniconda3/envs/teacher_gpt/lib/python3.11/site-packages/fastapi/routing.py", line 163, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/teacher_gpt/embed_api/api.py", line 100, in get_documents
    documentos = [df[df.hash_name == i].name.tolist()[0] for i in documentos]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'bool' object is not iterable
INFO:     127.0.0.1:39576 - "POST /load_context HTTP/1.1" 200 OK
